name: Archive Build Artifacts to GitHub Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        default: v.5.0.0

  # workflow_run:
  #   workflows: ["Release Please Workflow"]
  #   types:
  #     - completed

jobs:
  release-artifacts:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    strategy:
      matrix:
        board: [nrf9160dk/nrf9160/ns, nrf9161dk/nrf9161/ns, nrf9151dk/nrf9151/ns, thingy91/nrf9160/ns]

    steps:
      - name: Archive name generator
        id: artifact_name
        run: echo "artifact_name=$(echo ${{ matrix.board }} | tr "/" "_")" >> $GITHUB_OUTPUT

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.artifact_name }}

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.inputs.release_tag }} ${{ steps.artifact_name.outputs.artifact_name }}.zip
